"""empty message

Revision ID: bcfd119f9640
Revises: None
Create Date: 2016-11-06 14:25:45.496965

"""

# revision identifiers, used by Alembic.
revision = 'bcfd119f9640'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('texts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('author', sa.String(), nullable=False),
    sa.Column('author_birth_year', sa.Integer(), nullable=False),
    sa.Column('period_start_year', sa.Integer(), nullable=False),
    sa.Column('text_content', sa.Text(), nullable=False),
    sa.Column('gutenberg_id', sa.Integer(), nullable=False),
    sa.Column('bag_of_words_id', sa.Integer(), nullable=True),
    sa.Column('data_set', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('gutenberg_id'),
    sa.UniqueConstraint('title')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('texts')
    ### end Alembic commands ###
